1. Download the Dataset

2. Load the Dataset

In [1]:
import pandas as pd
data = pd.read_csv("Salaries.csv")

C:\Users\visha\AppData\Local\Temp\ipykernel_13824\1524202678.py:2: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Salaries.csv")

3. Display the First 10 Rows of the Dataset

In [2]:
data.head() #BY DEFAULT TOP 5 ROWS

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [3]:
data.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

4. Displat the Last 10 Rows of the Dataset

In [4]:
data.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [5]:
data.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

5. Find the Number of Rows and Columns of the Dataset using Shape

In [7]:
data.shape

(148654, 13)

In [8]:
print("Number of Rows : ",data.shape[0])
print("Number of Columns : ",data.shape[1])

Number of Rows :  148654
Number of Columns :  13

6. Complete Details about the Dataset

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

7. Check Nullvalues in the Dataset

In [10]:
data.isnull()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,False,False,False,False,False,False,False,False,False,False,True,False,False
148650,False,False,False,False,False,False,False,False,False,False,True,False,True
148651,False,False,False,False,False,False,False,False,False,False,True,False,True
148652,False,False,False,False,False,False,False,False,False,False,True,False,True
148653,False,False,False,False,False,False,False,False,False,False,True,False,False

In [11]:
data.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

8. Drop ID , Notes , Agency , and Status Columns

In [12]:
# STEP 1 : CHECK COLUMNS
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [ ]:
# STEP 2 : DROP COLUMNS and SAVE DATASET
data = data.drop(['Id','Notes','Agency','Status'],axis=1)

In [14]:
data.head(1)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011

9. Get Overall Statistics About the Dataset

In [16]:
data.describe(include="all")

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

10. Find the Occurence of the Employee Names (TOP 5)

In [17]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [18]:
data["EmployeeName"].value_counts().head()

EmployeeName
Kevin Lee       13
William Wong    11
Richard Lee     11
Steven Lee      11
John Chan        9
Name: count, dtype: int64

11. Find the Number of Unique Job Titles

In [20]:
data.columns
data["JobTitle"].nunique()

2159

12. Total Number of the Job Title Which Contains "CAPTAIN"

In [25]:
data.columns
data["JobTitle"]
data[data["JobTitle"].str.contains("CAPTAIN")]
len(data[data["JobTitle"].str.contains("CAPTAIN",case=False)])

552

13. Display All the Employee Names from the "Fire" Department

In [ ]:
data.columns
data["JobTitle"]
data[data["JobTitle"].str.contains("fire",case=False)]["EmployeeName"]

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

In [ ]:
data[data["JobTitle"].str.contains("fire",case=False)]["EmployeeName"].count()

"PATRICK GARDNERALSON LEEMICHAEL MORRISJOANNE HAYES-WHITEARTHUR KENNEYDAVID FRANKLINMARTY ROSSGEORGE GARCIAVICTOR WYRSCHJOSEPH DRISCOLLJOHN HANLEYRAYMOND GUZMANMONICA FIELDSJOSE VELOBRENDAN WARDMICHAEL THOMPSONTHOMAS ABBOTTTHOMAS SIRAGUSAMICHAEL THOMPSONBRYAN RUBENSTEINKEN YEEKIRK RICHARDSONMICHAEL ROLOVICHDARRYL HUNTERKENNETH SMITHCHARLES CRANEROBERT POSTELEDWARD ROLANDRICHARD BUSALACCHIKEVIN BURKEBERT REYESMICHAEL DELANEEDUARDO GONZALEZROBERT WINSLOWLORRIE KALOSJONATHAN BAXTERMICHAEL BRYANTMARY TSEMARK GONZALESPETE FAY JRREX HALEKEVIN SMITHGREGORY STANGLANDKEVIN TAYLORERIKA HOOLAUIFI SEUMAALAPATRIC STEELEMICHAEL WALSHSAMSON LAISCOTT SCHOLZENKHAIRUL ALIMICHAEL CASTAGNOLASEAN BONETTIJOHN HICKEYGLEN KOJIMOTOEDWARD CHUSOFIA MATHEWSEDMUND DEAZACHARY PUMPHREYMARK CASTAGNOLALUIS IBARRA-RIVERADONNIE HORNBUCKLETIM AREJARASMI CHANMICHAEL KEARNEYMATTHEW MCNAUGHTONKARL JURGENSONOSCAR CABRERAMARTIEN VERHAEGCARL JEPSENGEORGE LYSENKOHARRY PINKARDALBERTO PEDRUCODWAYNE CURRYLEON WHITENATHAN HARDYDENNIS SUTTERDONALD FIELDSSAMUEL ROMEROOLLIE BANKSTHOMAS HARVEYMARTIN BELTRANROBERT TAICHRISTOPHER HAZENPIERRE FRANCOISTROY JOLLIFFMICHAEL AHERNROBERT SERRANOJAMES VANNUCCHIPHILIP STEVENSTIMOTHY SULLIVANCANTREZ TRIPLETTNOEL MORONEYGERALD MANSUR JRALAN HARVEYWILLIAM RADERGREGORY MCFARLANDCLEMENTINO AVILA IIRYAN KENNEDYJOHN ROCCOARNOLD CHOYMIKE BREILINGANDREW LOGANGLENN KIRCHERTYRONE PRUITTBROOK MANCINELLICHAD LAWFERNANDO DEALBAROBERT STYLESEDMUND VAILANDREW SAITZARNIE LEEMITCHELL LEENEREE DASTOUSMELISSA LERMARAYMOND CHAVEZFREDERICK BINKLEYGUY GOODWINBERGLIOTH MATHEWSPABLO SIGUENZABRIAN MURPHYSTEVEN WILLIAMSMORGAN PETITIPAUL URQUIAGAJOHNSON YOUDANIEL YONTSDAVID THOMPSONJAMES BLAKECLYDE CHRISTOBALTHOMAS MURPHYGLENN ORTIZ-SCHULDTFERDINAND MENESESALVIN LAURYAN CREANSAMUEL NIETORUDY CASTELLANOSMICHAEL GONZALESJEFF IWASAKIJENNIFER DEBERRYALEC BALMYROBERT LOPEZGREGORY CACHARELISRONALD PRUYNJOHN KOSTARICKY HUIERNEST JOHNSONTERENCE OSULLIVANKEVIN KUHNMICHAEL MOYNIHANJOHN MURPHYJOSEPH CUFFMICHAEL SMITHDANIEL ARMENTAKENNETH CORDEROROBERT COLEMANNICOLETTE DIVECCHIOJIM HALL IIITHOMAS BUSBYDUSTIN NOVODAVID HAWKINSMAMI SUZUKI-VIDALONJALAL AINEBDANIEL MOLLOYVINCENT PAMPANINMARK JOHNSONBRENDAN MCGORRINATTICA BOWDENDALE CARNESVINCENT DAVISWILLIAM MCFARLANDSAHIR PUTRUSDENISE BAILEYANNETTE HOBRUCKER-PFEIFERCHUTEH KOTAKERAEMONA WILLIAMSJEFFREY BARDENMATTHEW CANNONROBERT GALLOTRICHARD UNTALANVERNONICA JONESANTHONY ROBINSONMANUEL PEGUEROSTHOMAS REYRICHARD CURRIEDEREK WINGDENNIS O'NEILLRUDOLPH ERLERGAVIN ESTUPINIANJEFF COLUMBINIANDRE WILLIAMSFLOYD ROLLINSTHOMAS KOHMANNHENRY LARKINRAUL FRANCISCONICOL JURATOVACDAVID ZWYERALAN REYNAUDPATRICK MULLANEYDENISE NEWMANDAVID OWENJOHN FLORESMICHAEL BELLOMAGALY SAADEJACK CHOWJOHN CREMENJULIO ESCOBARFRANK KOSTADERIO DITOROBERT MUHAMMADFRANK HSIEHEDWARD CAMPBELLLENETTE THOMPSONJOHN STANFIELDMATTHEW HUTCHINSONLOURDES RUSSELLDWIGHT NEWTONDAVID BROWNVINCENT NOLANABDUL KHADIRTERENCE WOORAYCARDO AVILESCHERISH MURDOCKLARS ASPELINRICHARD GERINGROBERT LA EACEMARY KUCELVITANI BENJAMINJORGE PLATARAMON SIMONANESTO ESTRELLAJANET BROCKTHOMAS FOGLEKENNETH HUPKEROHAN KNIGHTPATRICK GRIMESEYDONALD PEOPLESJOHN DARMANINEDWARD MOYPAUL JUGRONALD JOHANSENROMELIA SCOTTSTEVEN MILLERGREGORY ZANDERSMILTON YUENAARON FISHERSTEPHEN MAGUIREVINCENT WONGRONALD LEWINJESSE BAUTISTAJAMES HUDSONCARL DRAKE IIISARA COEJOSEPH SCHIEBOLDEDWARD BARBEROCHRISTINE EMMONSCHRISTOPHER PRATTJAMES KIRCHERDONALD GOGGINANTHONY BENDIKNORMAN CABAKENNETH COFFLINLORENZO IBARRADANIEL MARTINOERICK MARTINEZWILLIAM STORTIJONATHAN OKAMURAGREGORY PERATASEAN MCKINNEYDOUGLAS CALDERONGAVIN MCGOLDRICKEDDY WOOERNEST CARRILLOBROOK BAKERJOEL DELIZONNAROBERT REEDTODD PLUNKETTANTHONY WESTMATTHEW SCHWARTZALEXANDER DOUGLAS JRCHARLES HARDIMANARNOLD WOOBRUCE FINEMEIR GORDONANTENOR MOLLOYMARC PEARSONMANUEL ALVARENGAJOHN CHRISTYWILLIAM LAUDUSTIN WINNFERNANDO JUAREZGERALD HESSGERALD GAUERDAVID MORRISJEFFREY AMDAHLFRANCO CALZOLAIDAVID MONTEVERDICLAUDIA VALENTINOJAMES LOWEGLENN FREYERIC LEALMICHAEL RUBINKEITH ONISHITODD PRAKINMICHAEL MULLINSPENCER NAKAOTHERESE GEEGLEN ZORRILLAMICHELE GRINDSTAFFROBERT WONGDENNIS SULLIVANPATRICK RABBITTSCOTT SANDINELARRY JACOBSMICHAEL KIRKJOSEPH BARBEROJERRY CHIANGJAMES PERRY IIMICHAEL COLEMANDANIEL ROMEROMOISA TELLEZJAMES AYACHEERIC MONTALVOSTANLEY PERRIATTANNE TAMETHAN BANFORDCHRISTIAN COLLIERTIMOTHY NEFFJOHN SIKORAELLEN STEINVICTOR GONZALESDEAN WHITTAKERMICHAEL PATTJAMES KIMBALLCHRISTOPHER MADSENMATTHEW ALBAKAEO NACUAJEANINE NICHOLSONEDWARD LONDONOART RUIZJAMES DRAPERGABRIEL SHINTERRY SMERDELMATTHEW LANEDOUGLAS SPIKESWILLIAM WYCKOFFCHARLES MC COYMICHAEL HASTEYKENNETH LOMBARDIDAMEN TOLLIVERYUSUFU CAUNGULACHRISTOPHER DUGANLEONARD CAULDERRANDALL HIROPAUL GALLEGOSCONRAD BENITEZPAUL SHIMAZAKIRAUL SANDOVALLLOYD GOLDBERGMICHAEL HORTATRACY FRANTZSTEPHEN GIACALONETERENCE WHITEMARK MACIASELYSE DUCKETTAISHA KRIEGERBERNARD LANTINNICHOLAS BAZARINIBRIDGET CULLINANEJAMES QUIRKEGEORGE PETTYWILLIAM WONGANTHONY MARTINEZJAY CLELANDDESMOND COTTERCHASE WILSONMICHAEL JONESTYSON YEESTEVEN WOMBACHERJAMES OCONNELLALLEN WONGVICTOR WONGSTEPHEN CRUZSTEVEN BOKURARICHARD STEVENSSCOTT EBERHARTDANIEL BRIGHTBRIAN WALSHDAVID NONOMURAMARK HAYESJOSEPH GIACOMINIJASON BLANDMICHAEL KIRTLEYJEAN PINTOPAUL O'KANECHRISTOPHER POSEYSTEPHEN FINNEGANSOLA CHUOPPAUL MCDONAGHDAVID SPENCERJOSHUA PEREIRAMICHAEL CASTAINROGER PHILLIPSFRANK CERCOS IVERIK BROWNJOSHUA CUSICKDANIEL DECOSSIOKEVIN OSULLIVANK CARLTON BISCEVICDANIEL TAUBERJASON HARRELLEILEEN MCCRYSTLEALLEN WONGJANEEN PIROSKOKELLY HOLTJOSEPH HALLISYERIC STIVESONWARREN HOUSEMICHAEL LAWSONSHELIA HUNTERPHILIP TELESFOROSHAYNE KAIALOAEDWARD YUPANITA PARATLEYBARRY LOROBERT ARZAVENASH QUINTODEAN CRISPENRAFAEL GORDONRUBEN MONTEROBRANDON TOMJOEL SOTODAVID MURRAYNIKKI GRIFFEYJAMES ONOEPAUL SAITZMICHAEL TEUPELKAREN HEALDDANIEL FLEMINGEDWARD LABRADOMARIA NILSSONRICHARD MCGEEDARRYL LOOJONATHAN HUGGINSJOHN YEEMICHAEL SIMONRONALD LAURAMON BARRETO JRCLAUDIO RIVIECCIOSUSAN DEMARTINIGERALD SCULLIONJENNIFER MATHEWSKEVIN CHOCKERLISA MOYJAMES FEWELLJOSEPH SALLADYKATHLEEN HAROLDJULIE DEJARLAISDARIUS LUTTROPPEDWARD BANKSNEAL CAVELLINISHON BUFORDJOHN MURNANEDENISE PEMBERTONMICHAEL MAGALONGJOHN WONTHERESA FOGARTYCARL BARNESDANIEL BECKWITHJEFFREY COVITZRICHARD WENDLANDSIULAGI SALABERNARD MAGUIREJIRO YAMAMOTOMELCHOR PICARDALSTEPHEN CASSIDYJONATHAN LOWDAVID SAITZCHRIS SALASVALERIE STEPHENSON-BOYDSCOTT DARMSTADTADRIENNE SIMSDAVID LESTERJEREMY SILVAJOEL SATOCARLOS HOYKYLE MERKINSLORGE QUANTJAMES KOTTERTINA SEIBERTJOHN CABADOUGLAS MANGUIATMICHAEL FERRARAJON DEL BINOJEFFREY WONGRAYMOND LEEGAVIN MARCONIDAVID RUSSELLDOMINIC OTTOBONINEAL JAYMESREGINA MORLEYTOD STEPHENSONGEORGE SMITHANGELA ROMEROJOSEPH BEAMALEXANDER UNTALANJOE LUICHRISTOPHER HEUERMANJOHN GRANTSTEPHEN GONZALESDAVID RITTERWALTER VILLAVICENCIOLEONARDO HARRISEDWARD AMITMICHAEL DIETZENKEITH PHILLIPSMAURICE CASTAINKEVIN PARDINIBRUCE MARTINMARC KASPERJAY LEEAL GARZADANIEL CASEYJOE CHANKATHLEEN GILBRAITHMICHAEL COCHRANEJOHN HERNANDEZMIKAEL BAYLESSBRUCE SAMSONCRISTEO REYESDAVID CRESPINREUBEN RAMOSJASON REICHARDRICHARD NOLANRICK FIGARIRUDY GUAJARDOKATHRYN CARDINALEJARED KUNKELMICHAEL MALONEYRICHARD ESPINOZAKEVIN WALSHDAVID SMILEYMARCO NOCONJULIO DELUCCHITHOMAS JOHANNESSENGREG WYRSCHHENDRYCK LASAKWAYMAN DUNCANETHAN JACKSONCRAIG JOHNSONSTEVE SILVESTRICHCLIFTON HONGLAURA KELLYTAMI TURNERMARIBETH JENSENDEREK OLEARYDAISY YUJAMES MAC DONELLKJELL HARSHMANTHOMAS MCGUIREERIK ZAMMARCHISHAWN ZIMMERMANANDREW SOBOZINSKYMICHAEL MENEFEEMICHAEL JUANCAROLINE PRIEMRICHARD LOPESNATASHA PARKSBRUCE GUITRONGIDEON PRICEMICHAEL CHARLTONKEITH ALMIROLLUKE MICHAELISPATRICK D'ARCYLAWRENCE CONRADMICHAEL PETERSONGEOFFREY QUESADAROBERT VIGILBRUNO WALTHERMARK NICHOLASGILLIAN SMITHROBERT DOTSON IIIKENDRICK LOWMICHAEL MURPHYGABRIEL LOPEZBRIAN BURNSGREGORY COLLACOKENNETH MARTINKENNETH DUNNMICHAEL BARRYSTEPHEN CASSIDYLAWRENCE POWELLJANICE HAYESMICHAEL CAMPANALIROBERT KISHIDENNIS FOSTERCHARLES FARRUGIAFREDERICK REPPUNRONALD ROBINSONGERALD WHITEFRANK ROLDANALBERT BRONSON JRMICHAEL DAYTIMOTHY FARMERBRICE PEOPLESAMY SWANSONDAWN DEWITTJERRY SHEARNICHOLAS HOLLGREGORY STEWARTHEATHER PIPERDANIEL MCCLOSKEYMARC EVANSRANDALL HENDERSONRONALD CUPIDOALAN CAMARILLOPAUL CRAWFORDSTEPHEN ENGLERAARON STEVENSONROBERT SCHEPPLEREUGENE ADAMSCATHERINE EMMONS-SAMSONCONRAD BROSASBRENT STUCKERTDAVID D'AMICOKENNETH JONESKIMBERLY GRINTONMICHAEL VIEIRACYNTHIA LUCEROTODD WEDDLEHEIDI BERGMARKEDWARD MARTINEZGEORGE CERNAMEGAN FRANZENHANSJUERG ENZMICHAEL DUNCANYOON LEEBRIAN COLLINSJEFFERY CHINJUSTIN APOSTOLIMATTHEW LEESTEVE FIGUEROAJOSEPH VIGLIZZOCHRISTOPHER BONNGIL INTENGANANTHONY RIVERASCOTT DOONANCYNTHIA FAENZIANSON WUMARTA MCGOVERNJOSEPH DEVATYMICHAEL GUAJARDOCHARLES KWONGPAUL MANGIOLARONALD PEREZLAVERNE MALIGADARRYL BREWSTERJUSTIN SCHORRBRIAN MCCARTHYGREG TRUMPLERKENNETH MCCARTHYKINNIE JAMERSON JRERIC BOTELHOHARRY HIGGINSJOSHUA WILSONHERMAN WOOWILLIAM DAVISTHERESA WOLOWICDONYALE HOYEPETER GROSSJOSE ZALBAJAMES REIDYGARRETH MILLERMICHELLE MCCOYTHERESA KWANCHUCK WATANABEANTHONY SMERDELGARRET LUCIERJASON WATROUSRACHEL MARCICTIMOTHY MCHALERICKY YEEERICA ARTESEROSGENERAL JAMES JRMATTHEW TARLACHPETER LEEJAMES CARLINJOSEPH SILVATHOMAS THORNTONANTON SHELTONWILLIAM DORSEYMARK SIKORADAWN ROSALESEDWARD GHILARDI JRROBERT TURNQUISTDARRELL STONEMICHAEL CREEDONDOMINIC SHANLEYSEAN MULLANEDANIEL DOUGLASSWAYNE WONGDONALD BARRICKMICHAEL FUCCIOLORICHARD FAUSTALLEN BOGDANOFFCHRISTOPHER YOCKALVIN SELVAKATHY AUSTINBROCK WELLSADAM BUSTILLOSKIMBERLY MC KEONNICHOLAS PAYNEPATRICK BRYANEIGIL QWISTJOHN SHANLEYKENNETH DEVERDAVID PLANKANATHAN SZUTUDAVID SWEENEYANTHONY BRANCHCOMBJOHN K CHOYSALLY SAXTONEMMON LEWAMY ENGWILFREDO VARONAJAMES MELLBERGPAUL MCHUGHRAMON SERRANOTHOMAS KIERNANTERRY FITZSIMMONSMARTIN SPALKAGREGORY BLATMANIAN DERAMMELAERELYLE WOODSONTHOMAS OCONNORSTEVEN METZJASON SIMMONSRALPH BLANCHARDMARC DEVILLEJULIE MAUPATRICK SULLIVANTIMOTHY TIERNANHEIDI BOHLER BARNETTDAMON O'BRIENSEAN JOHNSTONKEVIN MC KEONDONNY BENDOTHOMAS OERTLICHRISTOPHER BENZPERRY CHOYJOHN DILUZIOKEVIN NIELSENJUSTIN BROWNREY BUZONWILLIAM CHINPETER ARNAUTOFFRICHARD COTTONCYNTHIA RICKERTCHADWICK ERTOLACECILIA JIANGKAAN CHINNANCY BARSOTTIMARY MINOGUEJOE NALDOLARRY PARATHEODORE CARTERMARCIEL RIVERAALLEN WUSHANE MURPHYJOHN CHUNGPHILIP LEEMANUEL LOPESIVAN GOMEZTOMIE KATODARREN BORTMASCHESTER SPIRLINKERBY LAUJOHN LOPESWILLIAM JACKSONMICHAEL PARKERJOHN DRAKESTEPHEN MARCOTTEEUGENE EDEN-JRROBERT NEUNEKERCRAIG LOUIEKIMBERLY HATCHERJASON WOODANIEL GRIFFINGREGORY SIMPSONTRACY O'KEEFFEMARY CARDERANDREW BIRKHOFFPHILIP BENSONSHERMAN TILLMANSHIRLEY SZELAKAREN KERRJOHN DUNNROBERT MELLOPATRICIA LEEMICHIE WONGREXIE MEGIAPATRICK MORANREBECCA ATWATERJEREMIAH RIBEIROTHOMAS HANEYTHORIN SHATTUCKSTEPHEN MC PARTLANJOHN CURDWILLIAM BOYLEROBERT MCDONALDVICTOR HURTADONATALIE LEVCHENKOWILLIAM LINNEYJANETTE NEVES RIVERASTANLEY LEERYAN TOBYBRYAN HENDONMICHAEL ORLANDOWILLIAM POWELLJAMES APPSCOTT HUAROBERT ZLATUNICHTHOMAS BOLLINGERFREDERICK PUTTMICHAEL MARKSJEFF RUSTEENCHARLES DALEYSHANE FRANCISCOROGER NGSAMUEL HOALAN WONGBRETT LYNCHOCTAVIO-JAME LEONARDOTIMOTHY KELLYPATRICK HIGGINSSEAN VISSERNATHAN SHAPIROMARK KANERICHARD SLATTERYROBYN GRALICERHUCKLEBERRY RAMSAYTIMOTHY WONGGREGORY JONESRAMON CHEAKRISTA SMITHJASON CHANANDREW THOMASJOHN LEMBERGLEONARDO CAVESTANYLAWRENCE YUPCLIFTON MERRILLKENNETH LINNEYJACK TAYLORCHRISTOPHER CANDIADANIELLE SORRENTIJEFFREY BABBKIMBERLY HIROSHIMASCOTT KINKADEJASON CORTEZANTHONY GARIBALDIMICHAEL SONGKENG YAN CHANMARIO ROMEROHEATHER BURENBRITTON SMITHRICHARD BROWNROBERT MILLERBRENT MARKSMICHAEL HOELSKENDANIEL GRACIAJOHN WILKOSZELMEN WUWILLA ORTEGAROBERT JONES IIJOEL NEWTONMARK HARDEMANBARRY WONGEMIL CUANJAMES KUCHARSZKYBRIAN BALLARDANNIE HODDINOTTSTEVE MULLERTIMOTHY HOWECHRISTOPHER SPEARJOHN FOGARTYWILLIAM YEUNGJAMES UNTALANDAT TRUONGMATTHEW SCOLAMATTHEW ADAMSJAMES MULHOLLANDMARIFI ESTEVESBRENDAN CORMACKMARY BOUCHERHENRY SCOBLE JRDWAYNE NEWTONYVETTE ORTEGACAROL WYLEYGEORGE KOUREMETIS JRANTHONY YEERICHARD MCCOOMICHAEL QUINNCOREY YEHNORMAN WONGMARIANO ELIAS JRALISON YEELANCE MARTINLEONEL TINGINGARY ALTENBERGMICHAEL MARTINEZRAYMOND POYDESSUSPAUL ORLANDOEILEEN NEEDHAMTHOMAS MANNIONSABINE BALDENRONALD VANPOOLMICKI JONESCAROL CONLEY-BODINPEDRO MARTINEZDANIEL LUILAIN SALSTRANDPRIVADO GUMABAYJOSEPH HORTONKETTY FEDIGANERIN MURPHYARAM MARAVILLASRUSSELL ZIMMERMANJOHN MANNINGCHARLES MCGOWAN-FACIANINICHOLAS YUENJOHN SILVA JRCRISTINA KOSTAAMADOR HERRERAJANICE HOAGLINKEVIN SHEAROBERT RAMIREZLESLIE WONGANDREW GLEASONHENRY TAMZACHARY TIBBITSMICHAEL RUSTIAFRANCES FOCHAEDWIN DIAZPAUL DAIJOWAYLEN WANGNICHOLAS HELMERELIZABETH LEAHYPATRICK HANNANJAMES FERRANTEGILBERT JACOBS JRPATRICK DOHERTYHUMBERTO PILARTETHOMAS O'BRIENALBERT HOMTILAFAIGA TA'APE JRRICHARD MILESOSBALDO GUTIERREZTRACY CAVARETTAHELEN KIEFFERDONNA SPIRLINSAGIV WEISS-ISHAIGREGORY BROWNEJAMES PARISHJOHN TUIASOSOPOKEN AINSWORTHJOHNATHAN ASHBROOKLEONOR SALDANAIRENE YBARRANORMAN YUPSEAN MATSUBAYASHINEIL HOPPERRUSSELL ROBYWARREN DERANTONIO VERNONPATRICIA FLOODROBERT CAPPAJOHN DANNER IIIDAMIAN GARCIASTEPHEN KLOSTERKEVIN TOMKIRT THOMASONTRACE MCCULLOCHDAVID DAWLEYGEORGE KARAWANNYSTEVEN WONGJOHN KOSITZINSHANNON STABILEKATHERINE ALBA-SWANSONBENJAMIN FRANKSMARK OHARAJOHN MCNULTYGAYLORD GABRIELBRIAN KYONOCARY BUTCHERCHRIS RAY-ROHANWAYNE CHEWJON SARGENTTIMOTHY FINCHRACHAEL ATCHISONALAN DE BELLALORI CLETHENFRANK BONALKRISTINA NELSONDIANE VAN DER HEIDENBRIAN BARDENSETH RUBENSTEINMELINDA TALMADGEFRANCIS SPERISEN IIIKATHLEEN MCELHENEYDAVID DUNGMATTHEW EGANGUILLERMO CASILLASSUEON WONGSTEVEN STRONGPAUL LEEMYRON SCOTTJOSEPH CERTAINMICHAEL CLARKDAVID CHAVEZPEDRO GONZALEZ JRROBERT BOUGHNJAMES BEEMJOEL ZERMENOELI CHANMICHAEL AGUILARMEGAN OCONNELLJOSHUA DICKERJARED FRANKLINAGUSTIN LARUEKEVIN KRAMERPATRICIA LUIRICHARD BRITTONGUADALUPE MARINLESTER LESAVOYDENNY ACOSTACLYDE WATARAIMATTHEW WAYNEGEARY HORIKIRIDAMIAN ORDUNABETTRIETTA KIMER SCHNELKERJON CORBETTROBERT COLLINSONJENNIFER WARDENDANIEL MARTINEZERIC KWANMIKE WONGEDWIN RAMOSHARRISON KONGMARK GRADNEYSASHA GRANDERAYMOND NGDAVID WATERSJAMES GREENROBBIN HEWITTWILLIAM MADSENJASON MISHLERKERRY MANNKEITH BARAKAKEVIN SALASSIG WALLENJENNIFER STOWANDRE BROWNJOHN HARRINGTONDAVID AMITUANAIMICHAEL TINVICTOR LUBETRONALD CADITANJUAN LA CHICAWILLIAM REILLYPATRICK MARTINEZMARIO FLAVIANIPAUL MC DERMOTTLARRY DEENDUSTIN RUFFDENNIS YUROBERT MATEIKKAILIN WATERMANJAMES LEONARDMIMI WOOAPRIL BASSETTFRANCISCO OCHOAROGER FONGSTEPHANIE MCKNIGHTPEDRO VIEIRAGREGORY LOUIEJENNIFER MARTINEZJOSHUA SMITHKEVIN KELLYTONY LEWJOSHUA HOYTANTONIO LUIS ROCHARICHARD ARCHIBALDGREGORY SAVINPAUL BARRYLAWRENCE RUSTIATHEODORA REILLYCOLIN MACKENZIEDENNIS KELLYROBERT RECENDEZJOHN CHEUNGDEAN LUNDIEKAISER LAMLAWANDA ANDERSONPATRICK MURPHYDEE LAUDAVID YIPETER WALKERMORGAN LEEDEWAYNE ECKERDTNORMAN KWANFRANCINE BRISTOWADAM WOODMARILYN CHAVEZSTEVEN SELCKFREDERICK STUMPPJOHN ROGERSMARK ZHANGPETER LIERIC STOREYDONALD PRICE JRWILLIAM BIGARANIBENJAMIN CANEDOERIC SOTODUANE RIVERAJOHNNY WILLIAMSCHRISTINE WILLIAMSCHRISTIAN JEFFREYDOMINIC BORDACHARELI THOMASAUDRY LEEROSS O'REILLYJOHN MAGUIRELARRY ABELLALAWRENCE JEWEDGAR COVARRUBIASMARILYN LUMMANUEL DACALANIOERIC TANIMURARENO BLANCHFIELDJOSHUA PARKSJONATHAN RIDERNICHOLAS BRADYKARL JURADODAVID AYMERICHERIC HIPPMICHAEL CARIONREYNER MEDINAMICHAEL SANDERSHENRY TASTORAMON FLORESK P KASHIMAERIC LOUIEGREGORY YOUNGSCOTT HELLESTOBRIAN JESSONDANIEL DUNNIGANCARLA MURPHYMICHAEL SHANLEYANTHONY DIRICCORICHARD HOMDAVID PAGANSEAN PASTORIGEORGE NONOMURAJANA WAKEFIELDHENRY CHOYCESAR GUILLENCHRISTINA GIBBSMARC LOPEZGEOFFREY CLAYTONKRISTOFER HETLANDDENNIS SYMATTHEW ZLATUNICHJASON WONGJIMMY YEESEAN ZAMBTHEODORE CREIGHTONJOSE ALBANOARMANDO LIMONCHAUNCEY FERGUSONROBERT MILICIDAVE DEJESUSVINCENT PEREZTHEODORE TOMLAWRENCE MCDONNELLCHRISTOPHER BLAIRDAVID KRIKORIANJOAQUINN VILLARREALJENNIFER PRESCOTTFRANK CUFFEDEREK POWELLJODY JIMENEZBELA CARREIRACHRISTIAN MURPHYNATALIE SPAELTIDANA POMPEOPAUL SANDIGOMICHAEL ORRMICHAEL FERRYSTEPHEN HARPERGABRIEL RODRIGUEZKRISTOPHER MOOREBRIAN WASHINGTONMILES YOUNGMARY CALLAHANSTEPHEN MORANSTEVEN RASCONDENNIS FRAZERDAVID KIMMELKATHLEEN ZEPEDAPATRICK SHEACORNELIUS LUCEYROBIN FARMERMACHEAL THOMAS JRLAINIE WALLINGJAMES MOGANNAMBARBARA BRITZMARCELLA MC CORMACKBRITTANY GREENESTEVEN BRANTLEYGEORGE DEBRUNNERMICHAEL HARPERROCK PLICHCIKALLEN POSEYJASON EAKLEJAMES SCHRICKJAY VEACHJEFFREY MARCALETTIGARY DITODAVID BRITTDEREK MURPHYJAMES CORMACKPATRICK CONNOLLYNATHANIEL OLIVASJAMES LOCKHARTJUDITH KLOFSTADCRISTOBAL GUAJARDO-JRBENJAMIN SOSINARTHUR KING JRWILLIAM CHENGJON LOWDAVID MAXIONRICHARD HOLBACKNANCY GALVINMEGAN BYRNEROBERT WILSONJENNIFER GLICKMANEDWARD ALEXANDERERIN YAMAMURADYLAN HAWHEETERESA CAVANAUGHDIEDRE GIBSONASHLEY JARDINESCOTT MCFALLBRIAN KANEHERMAN VIRAY JRHARRY H C YEEMARK OCONNORMARK AUSTRIANERIVALDO SANTOSJAMES NOVELLO JRDERYK LEEWILLIAM BARTELSCARLA KASPERCHRISTOPHER HAMILTONMATHEW FLUKEMARY MERAWPAUL BASSETTJAMES HODGINDAREN BRANNANNELSON AVELARDOYLE MILLERTRAVIS RAILBRANDON CHATHAMDEBORAH PALMERDENNIS GAMASTEPHEN SHAWKEVIN KLYSEJUSTIN DAVIDSONNIKO SHARKANTHONY VALERIODUSTIN NUNNERYJOHN MCGEEJENSEN RHODESESMOND MONROYJEFFERY MORENODENISE ELARMSJEANNE SEYLERMICHAEL CELONADAVID BRUZZONEASHLEY WERRINA MENDOZALESLEY SUDDUTHRYAN WATSONANTHONY VOIGHTSTEPHEN GIESEKERCHRISTOPHER BOUTILIERPETRA JOHNSONGERARDO ZAFFAMATTHEW BEANRHAYMOND VIZCARRAJARED COOPERJOHN GROSHONGDANIEL VERHAGEJENNIFER ISHIKAWATSZLAP KORYAN TOWNERMARC SANTOSKEVIN DAYNICHOLAS ALEXANDERMICHAEL HORTAJIMMY YANJOSEPH DEL GRANDEROBERT POTTERJONATHAN FUNGPETER ONGLAURA HOWLETTJENNIFER GREENEEDGARDO VERGARAEDWARD DUNNHAMID LOCKSELI PAYTONADAM LEWISCHRISTINA CLARKWILLIAM WONGGREGG TAKEUCHIKEITH WONGIRENE AGERMARTIN GREALISHMATHEW FAHRNERROBERT DUGGANVIRGINIA CHEUNGLISA HOLDCROFTKEVIN GARRYCLITON BAILEYMICHELLE ESTRADATAN NGUYENDAVID WHALEYSCOTT WARDSHANE PINAULAJONATHAN PETTEYDALE WINNIFORDBRENT BARNESMICHAEL DIGREBRIAN BUNAARTHUR JULATONJOHN MURPHYRYAN JAMISONJASON LANDIVARPRISCO SOMONTANDONALD KERN JRMARILYN BARTONERIC SADLERVINCENT MILANOTHEODORE ACKERSONJOHN KAVANAUGHPATRICIA FALLONCHRISTOPHER SANDOVALSAYUMI BRANNANALEC KAUFMEIBEK SCOTT-CHUNGTHOMAS JAQUYSHJENNIFER BALESTRIERICHRISTOPHER CHAMBREDAVID DRABBLEIRA BURROUGHSDESTIN REY TIANEROAARON STEVENSONSTEPHANA MCCLARANRENEE NICHOLSONTHOMAS RORITA KEARNSGREGORY WONGBRIAN MACHADOSTEVEN AGERCHE SORIANODEEPA WALANDJONATHAN HONDAPETER LEONARDJANE KANGROBERT GORDONKENNETH LINCOLNMICHAEL FIELDSSYLVIA RIVERAMATTHEW FARISCLARK IREYZACHARY BEATTYHENRY TRUONGTYRONE HARPERANDREW BURDA JRDANIEL NAKAGAWAJAMES BUSTAMENTECHRISTOPHER OLSENJARROD CARIOLAGREGORY GINOTTIKETRIC MAHONEYGAIL READDIEJESSE MAURERTINA LIUCATHERINE ABRAMSPATRICK REYESMICHAEL CRAIGALBERTO JAIMELOPEZTRAVIS HEMENEZDANIEL SANKEYPETER JOHNSONJOSEPH KILGOREANGELA FREEMANNICK OXFORDTRUC NGUYENMICHAEL KRICKENKENICHI NOGUCHIJAMES MCGUIGANDAMON ROBERTSONANGELO MANALOANNA RENSITHOMAS VANDERREEEDWIN MARSULLOSTEVEN RODRIGUEZJIMMY CHEUNGDOMINIC FASSOMATTHEW ESTRADAWILLIAM KNEISROBERT SCHWARTZHEATHER MCCARTHYMICHAEL CUDDYROBI TSESHAUN MOONEYDOMINIC FUENTESJAMES MOOREMARK CHERRINGTONLAURA ATTIAPETER GREENEVAN CONNORLARRY BRADSHAWSHERRI MERRICKTREMAINE FAGAJOHN DAL PORTOJOHN BENSONDAVID NGFELIX DUAGSARAH BARTELERIKA LOCKHARTJASON THOMPSONSAMUEL MOOREGREG BARRONDANIEL ARCINIEGAGERALD SHANNONALLISON KALHAMMERDARREN MILLERJAMES BARDENMICHAEL ESTRADATHOMAS BURGERSARAH HAMILTONJOHN FORBES-3CHARLES JOHNSONTHOMAS LEEPERROBERTO LUCHADEBRA TANISROCK CRAWFORDGary AltenbergJoanne Hayes-WhiteFrederick BinkleyDavid FranklinBrendan WardSamson LaiRudy CastellanosMarty RossRaymond GuzmanMichael RolovichMark GonzalesDarryl HunterMichael DelanePhilip StevensThomas SiragusaJoseph DriscollScott ScholzenPete Fay JrGregory StanglandArthur KenneyKevin TaylorRobert PostelKirk RichardsonKevin BurkeLorrie KalosJames VannucchiAlvin LauBryan RubensteinMichael ThompsonArnold ChoyKevin SmithRex HaleMike BreilingErika HooMartin BeltranRobert WinslowDouglas SpikesEdward ChuGeorge GarciaMichael BryantMatthew LaneShelia HunterMatthew McNaughtonCharles CraneMark JohnsonJeffrey BardenDwight NewtonGuy GoodwinRicky HuiKhairul AliPatrick D'ArcySamuel RomeroKyle MerkinsCarl JepsenMichael Gonza

14. Find the Maximum Minimum and Average BasePay

In [36]:
data.columns
data["BasePay"]
data["BasePay"].describe()

count     148049.0
unique    109900.0
top            0.0
freq         875.0
Name: BasePay, dtype: float64

15. Replace "Not Provided" to "Nan" from EmployeeName

In [40]:
import numpy as np
data.columns
data["EmployeeName"].replace("Not provided",np.nan)
data["EmployeeName"]=data["EmployeeName"].replace("Not provided",np.nan)
data["EmployeeName"]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

16. Drop the Rows Having 5 Missing Values

In [47]:
data.columns
data.isnull()
data.isnull().sum()
data.isnull().sum(axis=1)
data[data.isnull().sum(axis=1)==5]

Empty DataFrame
Columns: [EmployeeName, JobTitle, BasePay, OvertimePay, OtherPay, Benefits, TotalPay, TotalPayBenefits, Year]
Index: []

17. Find the Job Title of the ALBERT PARDINI

In [48]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [49]:
data["EmployeeName"]

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

In [50]:
data["EmployeeName"]=="ALBERT PARDINI"

0         False
1         False
2          True
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: EmployeeName, Length: 148654, dtype: bool

In [51]:
data[data["EmployeeName"]=="ALBERT PARDINI"]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011

In [52]:
data[data["EmployeeName"]=="ALBERT PARDINI"]["JobTitle"]

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

18. How Much ALBERT PARDINI Makes (+Benefits)

In [57]:
data.columns
data["EmployeeName"]
data["EmployeeName"]=="ALBERT PARDINI"
data[data["EmployeeName"]=="ALBERT PARDINI"]
data[data["EmployeeName"]=="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

19. Remove All Null Values or Missing Values From Dataset

In [70]:
data.isnull()
data.isnull().sum()
data.dropna(inplace=True)
data.isnull().sum()

EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
dtype: int64

In [72]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

20. Correcting Datatype of the Columns

In [73]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [ ]:
data['BasePay']
data['BasePay'].dtype

dtype('O')

In [78]:
data["BasePay"]=pd.to_numeric(data["BasePay"],errors="coerce")

In [79]:
data['BasePay']
data['BasePay'].dtype

dtype('float64')

21. Find the TOP 5 Most Common Jobs

In [89]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='object')

In [ ]:
data["JobTitle"]
data["JobTitle"].value_counts()
data["JobTitle"].value_counts().head()

JobTitle
Transit Operator                6975
Special Nurse                   4382
Registered Nurse                3725
Public Svc Aide-Public Works    2514
Police Officer 3                2411
Name: count, dtype: int64